<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zone</string>
	</array>
	<key>firstLineMatch</key>
	<string>^(.TTL|; zone)</string>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~Z</string>
	<key>name</key>
	<string>Zone File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$(INCLUDE|ORIGIN|TTL)</string>
			<key>name</key>
			<string>keyword.control.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.host</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.section.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\S+)\s+(IN)\s+(CNAME|HINFO|MINFO|PTR|WKS)\s+(\S+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.section.class</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.name-server</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(IN)\s+(NS)\s+(\S+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.host</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.section.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.address</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\S+)?\s*(IN)\s+(A)\s+(".*"|\S+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.host</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.section.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.text-string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\S+)?\s*(IN)\s+(TXT)\s+(".*"|\S+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.section.class</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mx-preference</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.mail-server</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(IN)\s+(MX)\s+(\d+)\s+(\S+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.section.class</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.primary-ns</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.hostmaster-email</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^@\s+(IN)\s+(SOA)\s+(\S+)\s+(\S+)\s+\(</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.zone</string>
	<key>uuid</key>
	<string>8BCB6477-8D52-42FE-ADAB-69C49DC9A3C8</string>
</dict>
</plist>
